#!/usr/bin/env python3
"""Keep generated project documentation synchronized with config and VERSION."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config" / "targets.json"
VERSION_FILE = ROOT / "VERSION"
README = ROOT / "README.md"
PROJECT_DESCRIPTION = ROOT / "docs" / "PROJECT_DESCRIPTION.md"
AUTOMATION = ROOT / "docs" / "AUTOMATION.md"

HEADPHONES_START = "<!-- SUPPORTED_HEADPHONES_START -->"
HEADPHONES_END = "<!-- SUPPORTED_HEADPHONES_END -->"
DESCRIPTION_START = "<!-- PROJECT_DESCRIPTION_START -->"
DESCRIPTION_END = "<!-- PROJECT_DESCRIPTION_END -->"
VERSIONING_START = "<!-- VERSIONING_START -->"
VERSIONING_END = "<!-- VERSIONING_END -->"

DESCRIPTION_LIMIT = 330
SEMVER_RE = re.compile(r"^\d+\.\d+\.\d+$")


def load_target_names() -> list[str]:
    data = json.loads(CONFIG.read_text(encoding="utf-8"))
    names: list[str] = []
    seen: set[str] = set()
    for target in data.get("targets", []):
        output_path = str(target["output_path"]).strip(" /")
        name = " ".join(part.strip() for part in output_path.split("/") if part.strip())
        key = name.casefold()
        if name and key not in seen:
            seen.add(key)
            names.append(name)
    return names


def load_version() -> str:
    version = VERSION_FILE.read_text(encoding="utf-8").strip()
    if not SEMVER_RE.fullmatch(version):
        raise RuntimeError(f"VERSION must use MAJOR.MINOR.PATCH, got {version!r}")
    return version


def build_description(names: list[str], version: str) -> str:
    prefix = f"OPRA → UAPP/ToneBoosters EQ converter v{version} with automatic Google Drive sync. Configured: "
    if not names:
        return prefix.rstrip() + " none"

    included: list[str] = []
    for name in names:
        remaining = len(names) - len(included) - 1
        candidate_items = included + [name]
        suffix = f"; +{remaining} more" if remaining > 0 else ""
        candidate = prefix + "; ".join(candidate_items) + suffix
        if len(candidate) <= DESCRIPTION_LIMIT:
            included.append(name)
        else:
            break

    remaining = len(names) - len(included)
    if not included:
        return prefix + f"{len(names)} configured targets"
    result = prefix + "; ".join(included)
    if remaining:
        result += f"; +{remaining} more"
    return result


def replace_generated_section(text: str, start: str, end: str, body: str) -> str:
    if start not in text or end not in text:
        raise RuntimeError(f"README is missing generated markers: {start} / {end}")
    before, rest = text.split(start, 1)
    _, after = rest.split(end, 1)
    return before + start + "\n" + body.rstrip() + "\n" + end + after


def replace_or_insert_section(
    text: str,
    start: str,
    end: str,
    body: str,
    anchor: str,
) -> str:
    has_start = start in text
    has_end = end in text
    if has_start != has_end:
        raise RuntimeError(f"Generated markers are incomplete: {start} / {end}")
    if has_start:
        return replace_generated_section(text, start, end, body)
    if anchor not in text:
        raise RuntimeError(f"Cannot insert generated section; missing anchor: {anchor}")
    block = start + "\n" + body.rstrip() + "\n" + end + "\n\n"
    return text.replace(anchor, block + anchor, 1)


def readme_versioning(version: str) -> str:
    return f"""## Versioning

Current project version: **v{version}**. The canonical value is stored in [`VERSION`](VERSION).

Versioning is automatic when the preset library changes:

- changing configured headphones in `config/targets.json` bumps the **minor** version;
- an OPRA update that changes generated presets without changing the configured headphone set bumps the **patch** version;
- a breaking converter change uses a **major** bump deliberately rather than automatically;
- a scheduled run with no generated changes does **not** change the version.

The version, supported-headphone list, and project description are regenerated by the same GitHub workflow that validates and builds the presets. No personal access token is required for this versioning system."""


def automation_versioning(version: str) -> str:
    return f"""## Automatic project versioning

The tracked [`VERSION`](../VERSION) file currently contains **{version}** and follows Semantic Versioning (`MAJOR.MINOR.PATCH`).

The `Update OPRA presets` workflow decides the bump only after a successful preset generation:

- **Minor** — `config/targets.json` changed in the triggering push. This represents a change to the managed headphone/variant set or its approved routing/selection configuration.
- **Patch** — the generated `output/` changed while the configured target file did not. This covers upstream OPRA changes that alter the managed preset library and converter changes that materially alter generated output.
- **Major** — intentionally changed by a maintainer for a breaking converter or preset-format change. Major versions are never guessed automatically.
- **No bump** — no configured-target change and no generated-output change. Daily scheduled checks therefore do not create version noise.

After deciding the version, the workflow regenerates the README and `docs/PROJECT_DESCRIPTION.md`, runs the test suite, and commits `VERSION`, generated output, and generated documentation together when anything changed.

This design deliberately uses the normal short-lived GitHub Actions `GITHUB_TOKEN` with `contents: write`. It does **not** store an Administration-level personal access token merely to keep GitHub's cosmetic About/Description field synchronized. The repository About text may remain a stable summary while the README and generated project description carry the current version and complete configured-headphone information."""


def main() -> None:
    names = load_target_names()
    version = load_version()
    description = build_description(names, version)

    readme = README.read_text(encoding="utf-8")
    headphone_list = "\n".join(f"- {name}" for name in names) if names else "- None configured"
    readme = replace_generated_section(readme, HEADPHONES_START, HEADPHONES_END, headphone_list)
    readme = replace_generated_section(readme, DESCRIPTION_START, DESCRIPTION_END, description)
    readme = replace_or_insert_section(
        readme,
        VERSIONING_START,
        VERSIONING_END,
        readme_versioning(version),
        "## Automatic updates",
    )
    README.write_text(readme, encoding="utf-8")

    project_text = (
        "# Project description\n\n"
        "This file is generated from `config/targets.json` and `VERSION`. "
        "Do not edit the description line manually.\n\n"
        f"{description}\n"
    )
    PROJECT_DESCRIPTION.write_text(project_text, encoding="utf-8")

    automation = AUTOMATION.read_text(encoding="utf-8")
    automation = replace_or_insert_section(
        automation,
        VERSIONING_START,
        VERSIONING_END,
        automation_versioning(version),
        "## 2. GitHub output → Google Drive",
    )
    AUTOMATION.write_text(automation, encoding="utf-8")

    print(f"Updated documentation for {len(names)} configured target(s) at v{version}.")
    print(description)


if __name__ == "__main__":
    main()
